### ISSUE TITLE
Error during playback in console format.(with every file)

### ISSUE THREAD

**Issue by Idol11112222** [drensin/Remixatron#26]
I'm here again! This time, playback in the command line version does not work for me. Using GIT CMD and Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
I enter: 
infinite_jukebox.py goodsoundname.mp3
It writes:
pygame 2.1.2 (SDL 2.0.18, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Users\GoodUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
C:\Users\GoodUserName\Remixatron\Remixatron.py:190: FutureWarning: Pass y=[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ... -1.5258789e-04
  -2.4414062e-04 -3.0517578e-04]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ...  6.1035156e-05
   6.1035156e-05  9.1552734e-05]], sr=44100 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  self.duration = librosa.core.get_duration(y,sr)
Traceback (most recent call last):
  File "C:\Users\GoodUserName\Remixatron\infinite_jukebox.py", line 319, in <module>
    display_playback_progress(v)
  File "C:\Users\GoodUserName\Remixatron\infinite_jukebox.py", line 139, in display_playback_progress
    window.addstr(y_pos, x_pos, buj_disp, curses.A_BOLD | curses.A_REVERSE | curses.A_STANDOUT )
_curses.error: addwstr() returned ERR

This happens with every file. If I save the file through the following command, the file will be readable.

infinite_jukebox.py goodsoundname.mp3 -duration 3600 -save goodsoundnameRemix

I need playback through the console, it's more convenient for me. Can you tell me what the problem is and decipher this text.
please...
i dont understand what he writes and im too lazy...

**Comment by drensin** [comment]
yeah.. Curses on Windows is broken.  I don't know any library that implements it correctly.  This the key error is this: window.addstr(y_pos, x_pos, buj_disp, curses.A_BOLD | curses.A_REVERSE | curses.A_STANDOUT )
_curses.error: addwstr() returned ERR

Honestly, I'm thinking of deprecating the command line version since I've made a lot of improvements to the Web UI version - especially in beat detection and clustering.
