### ISSUE TITLE
Simple frontend

### ISSUE THREAD

**Issue by GoldenChaos** [drensin/Remixatron#5]
A simple front-end with a drag-and-drop interface to play an audio file infinitely. Doesn’t have to be pretty, just more convenient than the terminal! Any plans for something like this?

**Comment by drensin** [comment]
I've been thinking about building a website, actually, but I have to figure out some client-side playback stuff before I can tackle that.  Alternately, I could (probably) build a GUI that's portable across Linux/Windows/Mac, but that would take some work.

Finally, (in the meantime), you can add a right context menu item for MP3s (or whatever extension) that just calls this script.  Then, you can just right click on your file and launch this.

**Comment by GoldenChaos** [comment]
I think a portable GUI would be much more ideal than a website, especially since this is for playing local files (as opposed to tracks from Spotify). If you need/want some design help I’d be more than happy to donate a few hours of my time this weekend and mock something up in sketch :)

Hadn’t thought about adding it to the context menu, that’s a great idea haha. Definitely going to do that for now!

**Comment by GoldenChaos** [comment]
I'm thinking about this again. I discovered Platypus (https://sveinbjorn.org/platypus), but I've been unsuccessful getting it working properly. If you could provide simple instructions, I'd love to be able to just drag a file onto a window and have it work.

Here are my Platypus app settings:

![Screen Shot 2019-03-09 at 8 30 49 PM](https://user-images.githubusercontent.com/1396727/54079416-48841500-42aa-11e9-9ff2-9b738746c7e3.png)


Buuuut I get this error when running inside my Platypus app:

![Screen Shot 2019-03-09 at 8 30 46 PM](https://user-images.githubusercontent.com/1396727/54079413-3f934380-42aa-11e9-8d26-d7aab2292135.png)

Any thoughts on getting it working inside Platypus?

**Comment by drensin** [comment]
It looks to me like maybe the environment you selected doesn't support the
curses library.  I see that "text window" is an interface option.  Maybe
there's an option for Curses (or Termcap) support in one of the options?

-dave

**Comment by GoldenChaos** [comment]
Here are the options it’s got:

![Screen Shot 2019-03-10 at 7 39 45 AM](https://user-images.githubusercontent.com/1396727/54084500-bd396c80-4307-11e9-8762-df94ee5356b7.png)

You can also set arguments:

![Screen Shot 2019-03-10 at 7 40 47 AM](https://user-images.githubusercontent.com/1396727/54084504-db06d180-4307-11e9-95ea-6fe56ec0fd31.png)

I don’t think there’s an _explicit_ option for Curses or Termcap anywhere, it would have to be manually set. I don’t know anything about those two things though to configure it properly.

**Comment by drensin** [comment]
I've created a web ui for this app. Please see the "Web UI" directory for more.  It also comes with some enhancements from the original version.  Closing this for now.
