### ISSUE TITLE
raise NoBackendError()

### ISSUE THREAD

**Issue by rickleberg** [drensin/Remixatron#8]
Hey, I'm kinda new in programming, but I really want to use this software. After some time trying to install this I managed to finally (kinda) make it work. but when I use this line of code to start it: 

dinkleberg@ubuntu:~/Desktop/Remixatron-master$ python infinite_jukebox.py '/home/dinkleberg/Desktop/Remixatron-master/audio.mp3' -verbose

it outputs this like in the images.
![screenshot from 2019-02-10 13-58-16](https://user-images.githubusercontent.com/47508156/52540230-28f5dd00-2d3c-11e9-81fd-3e71192f5077.png)
![screenshot from 2019-02-10 14-02-24](https://user-images.githubusercontent.com/47508156/52540261-986bcc80-2d3c-11e9-80a0-b5fcaa3fd011.png)

This is the text that shows up:

 [#         ] loading file and extracting raw audioTraceback (most recent call last):
                                                                                       File "infinite_jukebox.py", line 263, in <module>
                                                                                                                                           progress_callback=MyCallback, do_async=False, use_v1=args.use_v1)
                                                                      File "/home/dinkleberg/Desktop/Remixatron-master/Remixatron.py", line 164, in __init__
                        self.__process_audio()
                                                File "/home/dinkleberg/Desktop/Remixatron-master/Remixatron.py", line 187, in __process_audio
         y, sr = librosa.core.load(self.__filename, mono=False, sr=None)
                                                                          File "/home/dinkleberg/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 112, in load
                                         with audioread.audio_open(os.path.realpath(path)) as input_file:
                                                                                                           File "/home/dinkleberg/.local/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
                                                                                raise NoBackendError()
                                                                                                      audioread.NoBackendError

I'm using a Virtual Machine of Ubuntu, on windows 10 host. And after install it I had to turn on "stereo mix" on windows because the VM had no sound and showed up a error message on boot. Is that the problem?
Can someone help me or guide me how to fix this? Thanks in advance

**Comment by drensin** [comment]
you're missing ffmpeg on your system.  See here to fix:
https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/

**Comment by rickleberg** [comment]
Hi, sorry for the late answer.

I did what you said and it works when I save the audio remix using the example 3. It saves the file and it works like expected, but the other ones give me this error:
![screenshot from 2019-02-28 11-11-57](https://user-images.githubusercontent.com/47508156/53591997-3ceb6c80-3b8d-11e9-96d5-2ebf9b4e66ed.png)

But at least I can already use it, so it's fine by me. 

Thank you! This is an amazing software.
Best regards.

**Comment by drensin** [comment]
hmm... Exactly what command line did you use?

-dave

**Comment by rickleberg** [comment]
I used this one: python infinite_jukebox.py faixa4.mp3 -verbose
It loads, it says testing cluster, creating vector and everything but then it shows that error message.

**Comment by drensin** [comment]
just for a test, try it without the "-verbose bit" and let me know?

**Comment by rickleberg** [comment]
Without the "-verbose" it loads again and says testing cluster, vector, and shows this:
![screenshot from 2019-02-28 12-36-54](https://user-images.githubusercontent.com/47508156/53596912-cce2e380-3b98-11e9-9f3e-dc0c1714fb77.png)

**Comment by drensin** [comment]
most curious... Can you attach your file, please?

**Comment by rickleberg** [comment]
Yes Sir. It happens with every song that I try, but when I say to save the audio it works fine.

Here is the google drive folder.
https://drive.google.com/drive/folders/1ierH13Jp_nEIoDtIW_2M8YPuELc1DP-l?usp=sharing

**Comment by Mar2ck** [comment]
I had this exact error as well. I used pip3 instead of pip and python3 instead of python for commands and now it works

**Comment by drensin** [comment]
In general, Python 2.7 is going away on Jan 1st, so I'm not supporting it anymore.  You should be using Python 3 (preferably 3.6+ and in a Virtualenv) for this code.
